---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/ubt-2204-amd64.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#
# Source(s):
#   - https://www.zabbix.com/download?zabbix=6.0&os_distribution=ubuntu&os_version=22.04&components=agent&db=&ws=
#
- name: "Download & Install deb package"
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu22.04_all.deb"
    state: present

- name: "Update & Upgrade"
  ansible.builtin.apt:
    upgrade: dist
    
- name: "Install Zabbix-agent"
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent"
  ansible.builtin.template:
    src:  zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "enable zabbix agent on startup"
  ansible.builtin.systemd_service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp"
  community.general.ufw:
    rule: allow
    port: "10050"
    proto: tcp

- name: "Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp"
  community.general.ufw:
    rule: allow
    port: "10051"
    proto: tcp
