---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#   Playbook for deploying Zabbix Agent

# -- Zabbix Agent 7.xx LTS --
- name: "Install Zabbix Agent 7.xx LTS (Ubuntu 24.04LTS) on host '{{ ansible_hostname }}'"
  include_tasks: tasks/7/ubuntu/2404.yml
  when:
    - ansible_distribution_version == "24.04"
    - ansible_architecture == "x86_64"
    - zbx_version == "7"

- name: "Install Zabbix Agent 7.xx LTS (Windows 64bit) on host '{{ ansible_hostname }}'"
  include_tasks: tasks/6/windows/win-64bit.yml
  when:
    - ansible_os_family == "Windows"
    - zbx_version == "7"

- name: "Firewall rule to allow Zabbix Passive (10050) on TCP port 10050 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall_rule:
    name: Zabbix Passive (10050/tcp) ** Managed by ansible **
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when:
    - ansible_os_family == "Windows"
    
- name: "Firewall rule to allow ICMPv4 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall_rule:
    name: Firewall rule to allow ICMPv4
    localport: any
    action: allow
    direction: in
    protocol: ICMPv4
    profiles: Domain
    state: present
    enabled: true
  when:
    - ansible_os_family == "Windows"   

# -- Zabbix Agent 6.xx LTS --

- name: "Install Zabbix Agent 6.xx LTS (Ubuntu 22.04LTS) on host '{{ ansible_hostname }}'"
  include_tasks: tasks/6/ubuntu/2204.yml
  when:
    - ansible_distribution_version == "22.04"
    - ansible_architecture == "x86_64"
    - zbx_version == "6"

- name: "Install Zabbix Agent 6.xx LTS (Ubuntu 24.04LTS) on host '{{ ansible_hostname }}'"
  include_tasks: tasks/6/ubuntu/2404.yml
  when:
    - ansible_distribution_version == "24.04"
    - ansible_architecture == "x86_64"
    - zbx_version == "6"
    
- name: "Install Zabbix Agent 6 (Windows 64bit) on host '{{ ansible_hostname }}'"
  include_tasks: tasks/6/windows/win-64bit.yml
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture2 == "x86_64"
    - zbx_version == "6"
