---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/ubt-2204-amd64.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#
# Source(s):
#   - https://www.zabbix.com/download?zabbix=6.0&os_distribution=ubuntu&os_version=22.04&components=agent&db=&ws=
#
- name: "Download & Install deb package"
  apt:
    deb: "{{ https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu22.04_all.deb }}"
    state: present

- name: "Update & Upgrade"
  apt:
    upgrade: dist
    
- name: "Install Zabbix-agent"
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent"
  template:
    src:  zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "enable zabbix agent on startup"
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp"
  ufw:
    rule: allow
    port: "10050"
    proto: tcp
    # from_ip: "{{ zbx_server }}"

- name: "Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp"
  ufw:
    rule: allow
    port: "10051"
    proto: tcp
    # to_ip: "{{ zbx_server }}"

#- name: "Disable i386 repositories"
#  ansible.builtin.replace:
#    path: /etc/apt/sources.list.d/zabbix.list
#    regexp: deb http://repo.zabbix.com/zabbix/5.0/ubuntu focal main
#    replace: deb [arch=amd64]  http://repo.zabbix.com/zabbix/5.0/ubuntu focal main
    
    
