---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/ubt-2004-amd64.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#

- name: "Download & Install deb package"
  apt:
    deb: "{{ zbx_repository }}"
    state: present

- name: "Update & Upgrade"
  apt:
    upgrade: dist
    
- name: "Install Zabbix-agent"
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent"
  template:
    src:  zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "enable zabbix agent on startup"
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp"
  ufw:
    rule: allow
    port: "10050"
    proto: tcp
    from_ip: "{{ result_zbx_ip_passive.stdout }}"

- name: "Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp"
  ufw:
    rule: allow
    port: "10051"
    proto: tcp
    to_ip: "{{ result_zbx_ip_active.stdout }}"

- name: "Disable i386 repositories"
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/zabbix.list
    regexp: deb http://repo.zabbix.com/zabbix/5.0/ubuntu focal main
    replace: deb [arch=amd64]  http://repo.zabbix.com/zabbix/5.0/ubuntu focal main
