---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/7/windows/win-zbx7-amd64.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#
- name: "Set facts for Zabbix agent version that can be found in defaults/main.yml or overwritten in your playbook"
  ansible.builtin.set_fact:
    zbx_agt_win_src                 : '{{ zbx_agt_win_src_7 }}'
    zbx_agt_win_checksum            : '{{ zbx_agt_win_checksum_7 }}'
    zbx_agt_win_checksum_algorithem : '{{ zbx_agt_win_checksum_algorithem_7 }}'

- name: "Set variable 'zbx_agt_HostMetadata' to 'Microsoft,Windows' for autoregistration when is empty on host for auto registration '{{ ansible_hostname }}'"
  ansible.builtin.set_fact:
    zbx_agt_HostMetadata: "Microsoft,Windows"
  when: zbx_agt_HostMetadata|length > 0

- name: "Check if Zabbix service is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
  register: zbx_result
  ignore_errors: True

- name: "Stop service Zabbix agent when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: disabled
    state: stopped
  when:
    - zbx_result.exists == True and zbx_state == 'install'
    
- name: "Uninstall Zabbix agent when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --uninstall
  when:
    - zbx_result.exists == True and zbx_state == 'install'

- name: "Remove local Ansible repository when exists and zbx_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: absent
  when:
    - zbx_result.exists == True and zbx_state == 'install'
    
- name: "Create local Ansible repository when not exists and zbx_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: directory
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Download Zabbix Agent (Zip version) from url '{{ zbx_agt_win_src }}' to dest '{{ zbx_pkg_local_repository }}\\zabbix-agent.zip' on host '{{ ansible_hostname }}'"
  ansible.windows.win_get_url:
    url: "{{ zbx_agt_win_src }}"
    dest: "{{ zbx_pkg_local_repository }}\\zabbix-agent.zip"
    checksum: "{{ zbx_agt_win_checksum }}"
    checksum_algorithm: "{{ zbx_agt_win_checksum_algorithem }}"
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Unpack {{ zbx_pkg_local_repository }}\\zabbix-agent.zip to 'C:\\Zabbix\\' on host '{{ ansible_hostname }}'"
  community.windows.win_unzip:
    src: "{{ zbx_pkg_local_repository }}\\zabbix-agent.zip"
    dest: C:\Zabbix\
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Transfer and configure template 'zabbix_agentd.win.conf.j2' to directory 'C:\\Zabbix\\conf\\zabbix_agentd.conf' on host '{{ ansible_hostname }}'"
  ansible.windows.win_template:
    src: zabbix_agentd.win.conf.j2
    dest: C:\Zabbix\conf\zabbix_agentd.conf
    force: yes

- name: "Install Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --install
  when: 
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Start Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: auto
    state: started

- name: "Cleanup local repository '{{ zbx_pkg_local_repository }}' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: absent
    
- name: "Firewall rule to allow Zabbix Passive (10050) on TCP port 10050 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall:
    name: Zabbix Passive (10050) ** Managed by Ansible **
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: false
    
- name: "Firewall rule to allow ICMPv4 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall:
    name: Firewall rule to allow ICMPv4
    localport: any
    action: allow
    direction: in
    protocol: ICMPv4
    profiles: Domain
    state: present
    enabled: true
