---
# Title: Handlers for Zabbix agent
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: handlers/main.yml
#
# Description:
#   Handlers for stopping/starting/restarting services.
#
- name: "restart_zabbix_agent"
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
    masked: no

- name: "restart_win_zbx_agent"
  ansible.windows.win_service:
    name: Zabbix Agent
    state: restarted

