---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/6/windows/win-64bit.yml
#
# Description:
#   Playbook for deploying Zabbix Agent

# -- Set facts for Zabbix Agent --
#- name: "Set URL for downloading Zabbix Agent" 
#  ansible.builtin.set_fact:
#    zbx_agt_win_src             : '{{ zbx_agt_win_src_6 }}'
#    zbx_agt_win_checksum        : '{{ zbx_agt_win_checksum_6 }}'
#    zbx_agt_checksum_algorithem : '{{ zbx_agt_checksum_algorithem_6 }}'

- name: "Set variable 'zbx_agt_HostMetadata' to 'Microsoft,Windows' for autoregistration when is empty on host for auto registration '{{ ansible_hostname }}'"
  ansible.builtin.set_fact:
    zbx_agt_HostMetadata: "Microsoft,Windows"
  when: zbx_agt_HostMetadata|length > 0

- name: "Check if Zabbix service is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
  register: zbx_result
  ignore_errors: True

- name: "Stop service Zabbix agent when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: disabled
    state: stopped
  when:
    - zbx_result.exists == True and zbx_state == 'install'
    
- name: "Uninstall Zabbix agent when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --uninstall
  when:
    - zbx_result.exists == True and zbx_state == 'install'

- name: "Remove local Ansible repository when exists and zbx_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: absent
  when:
    - zbx_result.exists == True and zbx_state == 'install'
    
- name: "Create local Ansible repository when not exists and zbx_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: directory
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Download Zabbix Agent (Zip version) from url '{{ zbx_agt_win_src_6 }}' to dest '{{ zbx_pkg_local_repository }}\\zabbix-agent.zip' on host '{{ ansible_hostname }}'"
  ansible.windows.win_get_url:
    url: "{{ zbx_agt_win_src_6 }}"
    dest: "{{ zbx_pkg_local_repository }}\\zabbix-agent.zip"
    checksum: "{{ zbx_agt_win_checksum_6 }}"
    checksum_algorithm: "{{ zbx_agt_checksum_algorithem_6 }}"
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Unpack {{ zbx_pkg_local_repository }}\\zabbix-agent.zip to 'C:\\Zabbix\\' on host '{{ ansible_hostname }}'"
  community.windows.win_unzip:
    src: "{{ zbx_pkg_local_repository }}\\zabbix-agent.zip"
    dest: C:\Zabbix\
  when:
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Transfer and configure template 'zabbix_agentd.win.conf.j2' to directory 'C:\\Zabbix\\conf\\zabbix_agentd.conf' on host '{{ ansible_hostname }}'"
  ansible.windows.win_template:
    src: zabbix_agentd.win.conf.j2
    dest: C:\Zabbix\conf\zabbix_agentd.conf
    force: yes
  notify:
    - restart_win_zbx_agent

- name: "Install Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --install
  when: 
  - zbx_result.exists == False or zbx_state == 'install'

- name: "Start Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: auto
    state: started

- name: "Cleanup local repository '{{ zbx_pkg_local_repository }}' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: absent
    
- name: "Firewall rule to allow Zabbix Passive (10050) on TCP port 10050 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall:
    name: Zabbix Passive (10050)
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present

- name: "Firewall rule to allow ICMPv4 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall:
    name: Firewall rule to allow ICMPv4
    localport: any
    action: allow
    direction: in
    protocol: ICMPv4
    profiles: Domain
    state: present
    enabled: yes
