---
# Title: Zabbix agent install Windows
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/windows/zabbix-agent-install-windows.yml
#
# Description:
#   Taskfile for installing Zabbix Agent on a Windows.
#
- name: "Set variable 'zabbix_agent_HostMetadata' to 'Microsoft,Windows' for autoregistration when is empty on host for auto registration '{{ ansible_hostname }}'"
  ansible.builtin.set_fact:
    zabbix_agent_HostMetadata: "Microsoft,Windows"
  when:
    - zabbix_agent_HostMetadata|length > 0
    
- name: "Check if Zabbix {{ zabbix_agent_win_version }} service is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
  register: zbx_result
  ignore_errors: True

- name: "Stop service Zabbix agent {{ zabbix_agent_win_version }} when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: disabled
    state: stopped
  when: zbx_result.exists == True and zabbix_state == 'install'
    
- name: "Uninstall Zabbix agent {{ zabbix_agent_win_version }} when exist and is installed on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --uninstall
  when: zbx_result.exists == True and zabbix_state == 'install'
    
- name: "Remove local Ansible repository when exists and zabbix_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zabbix_package_local_repository }}"
    state: absent
  when: zbx_result.exists == True and zabbix_state == 'install'
      
- name: "Create local Ansible repository when not exists and zabbix_state is 'install' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zabbix_package_local_repository }}"
    state: directory
  when: zbx_result.exists == False or zabbix_state == 'install'
  
- name: "Download Zabbix Agent {{ zabbix_agent_win_version }} (Zip version) from url '{{ zabbix_agent_win_src }}' to dest '{{ zabbix_package_local_repository }}\\zabbix-agent.zip' on host '{{ ansible_hostname }}'"
  ansible.windows.win_get_url:
    url: "{{ zabbix_agent_win_src }}"
    dest: "{{ zabbix_package_local_repository }}\\zabbix-agent.zip"
    checksum: "{{ zabbix_agent_win_checksum }}"
    checksum_algorithm: "{{ zabbix_agent_win_checksum_algorithem }}"
  when: zbx_result.exists == False or zabbix_state == 'install'
  
- name: "Unpack {{ zabbix_package_local_repository }}\\zabbix-agent.zip to 'C:\\Zabbix\\' on host '{{ ansible_hostname }}'"
  community.windows.win_unzip:
    src: "{{ zabbix_package_local_repository }}\\zabbix-agent.zip"
    dest: C:\Zabbix\
  when: zbx_result.exists == False or zabbix_state == 'install'

- name: "Transfer and configure template 'zabbix_agentd.win.conf.j2' to directory 'C:\\Zabbix\\conf\\zabbix_agentd.conf' on host '{{ ansible_hostname }}'"
  ansible.windows.win_template:
    src: templates/windows/zabbix_agentd.win.conf.j2
    dest: C:\Zabbix\conf\zabbix_agentd.conf
    force: yes
  when: zabbix_install_version == item.version
    
- name: "Install Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_command: C:\Zabbix\bin\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.conf --install
  when: zbx_result.exists == False or zabbix_state == 'install'

- name: "Start Windows service 'Zabbix Agent' on host '{{ ansible_hostname }}'"
  ansible.windows.win_service:
    name: Zabbix Agent
    start_mode: auto
    state: started
  when: zabbix_install_version == item.version
  
- name: "Cleanup local repository '{{ zabbix_package_local_repository }}' on host '{{ ansible_hostname }}'"
  ansible.windows.win_file:
    path: "{{ zabbix_package_local_repository }}"
    state: absent
  when: zabbix_install_version == item.version

- name: "Firewall rule to allow Zabbix Passive (10050) on TCP port 10050 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall_rule:
    name: Zabbix Passive (10050/tcp) ** Managed by ansible **
    localport: 10050
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when: zabbix_install_version == item.version

- name: "Firewall rule to allow ICMPv4 on host '{{ ansible_hostname }}'"
  community.windows.win_firewall_rule:
    name: Firewall rule to allow ICMPv4 ** Managed by ansible **
    localport: any
    action: allow
    direction: in
    protocol: ICMPv4
    profiles: Domain
    state: present
    enabled: true
  when: zabbix_install_version == item.version
