---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/ubuntu/zabbix-agent-install-ubuntu.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#
# Source(s):
#   - https://www.zabbix.com/download?zabbix=6.0&os_distribution=ubuntu&os_version=22.04&components=agent&db=&ws=
#
- name: "Download & Install deb package on host '{{ ansible_hostname }}'"
  ansible.builtin.apt:
    deb: "{{ item.ubuntu_source }}"
    state: present

- name: "Update & Upgrade APT on host '{{ ansible_hostname }}'"
  ansible.builtin.apt:
    upgrade: dist
    
- name: "Install Zabbix-agent on host '{{ ansible_hostname }}'"
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent on host '{{ ansible_hostname }}'"
  ansible.builtin.template:
    src:  templates/ubuntu/zabbix_agent.confd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "enable zabbix agent on startup on host '{{ ansible_hostname }}'"
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic from Zabbix server to Zabbix Agent (Active on port 10051/tcp / Passive on port 10050/tcp) on host '{{ ansible_hostname }}'"
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: '10050', proto: 'tcp', desc: 'Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp' }
    - { port: '10051', proto: 'tcp', desc: 'Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp' }
