---
# Title: role-zabbix-agent
#
# Author: bitfinity-nl
# File: tasks/6/ubuntu/2204.yml
#
# Description:
#   Playbook for deploying Zabbix Agent
#
# Source(s):
#   - https://www.zabbix.com/download?zabbix=6.0&os_distribution=ubuntu&os_version=22.04&components=agent&db=&ws=
#
- name: "Set variable 'zbx_agt_HostMetadata' to 'Linux,Ubuntu' for autoregistration when is empty on host for auto registration '{{ ansible_hostname }}'"
  ansible.builtin.set_fact:
    zbx_agt_HostMetadata: "Linux,Ubuntu"
  when: zbx_agt_HostMetadata|length > 0
  
- name:  "Download & Install deb package for Zabbix 6.xx on host '{{ ansible_hostname }}'"
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu22.04_all.deb"
    state: present

- name: "Update & Upgrade APT on host for Zabbix 6.xx on host'{{ ansible_hostname }}'"
  ansible.builtin.apt:
    upgrade: dist
    
- name: "Install Zabbix-agent for Zabbix 6.xx on host '{{ ansible_hostname }}'"
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: "Configure Zabbix-agent for Zabbix 6.xx on host '{{ ansible_hostname }}'"
  ansible.builtin.template:
    src:  templates/6/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  notify:
    - restart_zabbix_agent

- name: "Enable systemd zabbix agent for Zabbix 6.xx on startup on host '{{ ansible_hostname }}'"
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: "Allow traffic between Zabbix server and Zabbix 6.xx agent (Active on port 10051/tcp / Passive on port 10050/tcp) on host '{{ ansible_hostname }}'"
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: '10050', proto: 'tcp', desc: 'Allow traffic from Zabbix server to Zabbix Agent (Passive) on port 10050/tcp' }
    - { port: '10051', proto: 'tcp', desc: 'Allow traffic from Zabbix agent to Zabbix server (Active) on port 10051/tcp' }
